### ISSUE TITLE
Pub version conflicts

### ISSUE THREAD

**Issue by TheNightmanCodeth** [draw-dev/DRAW#102]
> Because ini 1.1.0 requires SDK version <2.0.0 and no versions of ini match >1.1.0 <2.0.0, ini ^1.1.0 is forbidden.

This is what my local machine complains about when I run it. On `pub.dartlang.org`, a similar error is displayed [here.](https://pub.dartlang.org/documentation/draw/latest/log.txt)

>Because draw depends on color >=0.2.0 which requires SDK version <2.0.0, version solving failed.

How can this be? I check both `color` and `ini` pubspec files and neither of them require a dart SDK less than 2.0.

**Comment by bkonyi** [comment]
Both the `color` and `ini` packages haven't had their SDK versions updated since the Dart 2 release which is causing this issue. I've filed an issue for the color package (MichaelFenwick/Color#21) but I'm afraid the ini package is probably no longer maintained so I'll have to create a fork with the updated version.

In the meantime, you should be able to add the following to your pubspec.yaml to get around this for now:
```yaml
dependency_overrides:
  color: 2.0.2
  ini: 1.1.0
```

**Comment by TheNightmanCodeth** [comment]
That fixed it for me, thanks!

**Comment by bkonyi** [comment]
Glad that fixed it! I'll reopen this for now until the underlying issue is fixed just so I don't forget.

**Comment by bkonyi** [comment]
I've gone ahead and forked `ini` and `color` and updated the pubspec.yaml to point to those forks instead. You should be able to get rid of the dependency overrides after you update to version 0.4.1.
